//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanoiBusSystemManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemBanVeThang
    {
        public DiemBanVeThang()
        {
            this.NhanVienBanVeThangs = new HashSet<NhanVienBanVeThang>();
        }
    
        public int MaDiemBanVeThang { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
    
        public virtual ICollection<NhanVienBanVeThang> NhanVienBanVeThangs { get; set; }
    }
}
