//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanoiBusSystemManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_busEntities : DbContext
    {
        public db_busEntities()
            : base("name=db_busEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BanVeNgay> BanVeNgays { get; set; }
        public DbSet<BanVeThang> BanVeThangs { get; set; }
        public DbSet<DiemBanVeThang> DiemBanVeThangs { get; set; }
        public DbSet<LuuThong> LuuThongs { get; set; }
        public DbSet<NhanVienBanVeThang> NhanVienBanVeThangs { get; set; }
        public DbSet<NhanVienVanPhong> NhanVienVanPhongs { get; set; }
        public DbSet<PhongBan> PhongBans { get; set; }
        public DbSet<PhuXe> PhuXes { get; set; }
        public DbSet<TaiXe> TaiXes { get; set; }
        public DbSet<TuyenXe> TuyenXes { get; set; }
        public DbSet<VeNgay> VeNgays { get; set; }
        public DbSet<VeThang> VeThangs { get; set; }
        public DbSet<XeBuyt> XeBuyts { get; set; }
    }
}
