//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanoiBusSystemManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongBan
    {
        public PhongBan()
        {
            this.NhanVienVanPhongs = new HashSet<NhanVienVanPhong>();
        }
    
        public int MaPhongBan { get; set; }
        public string TenPhongBan { get; set; }
    
        public virtual ICollection<NhanVienVanPhong> NhanVienVanPhongs { get; set; }
    }
}
