//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanoiBusSystemManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiXe
    {
        public TaiXe()
        {
            this.LuuThongs = new HashSet<LuuThong>();
        }
    
        public int MaTaiXe { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string SoCMTND { get; set; }
        public string AnhCaNhan { get; set; }
        public string LoaiBang { get; set; }
        public Nullable<int> MaTuyenXe { get; set; }
    
        public virtual ICollection<LuuThong> LuuThongs { get; set; }
        public virtual TuyenXe TuyenXe { get; set; }
    }
}
