//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanoiBusSystemManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeNgay
    {
        public VeNgay()
        {
            this.BanVeNgays = new HashSet<BanVeNgay>();
        }
    
        public int MaVeNgay { get; set; }
        public string TenVeNgay { get; set; }
        public int DonGia { get; set; }
        public Nullable<int> MaTuyenXe { get; set; }
    
        public virtual ICollection<BanVeNgay> BanVeNgays { get; set; }
        public virtual TuyenXe TuyenXe { get; set; }
    }
}
