//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanoiBusSystemManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XeBuyt
    {
        public XeBuyt()
        {
            this.LuuThongs = new HashSet<LuuThong>();
        }
    
        public int MaXeBuyt { get; set; }
        public string BienKiemSoat { get; set; }
        public string HangSanXuat { get; set; }
        public Nullable<int> NamSanXuat { get; set; }
        public Nullable<int> SoGhe { get; set; }
        public Nullable<int> MaTuyenXe { get; set; }
    
        public virtual ICollection<LuuThong> LuuThongs { get; set; }
        public virtual TuyenXe TuyenXe { get; set; }
    }
}
